### ISSUE TITLE
Liveness and Readiness probe fail to quickly

### ISSUE THREAD

**Issue by john-zielke-snkeos** [treeverse/charts#143]
When installing the lakefs Chart into my local cluster, the lakefs pod seems to take more than 30 seconds to startup. Because of the configured liveness (and readiness) probes (default period/interval of 10s with failureTreshold of 3), the container is therefore deemed unhealthy and terminated before it can finish the startup. This causes an infinite restart loop with CrashLoopBackoff. If this is not an issue limited to my setup, could we modify the probes? E.g. increase the failureThreshold or the interval between the individual probe executions. I manually increased the failureThreshold to 12 retries on my deployments and that fixed the issue.

**Comment by Isan-Rivkin** [comment]
Hi @john-zielke-snkeos , done in #158  and released in [0.8.3](https://github.com/treeverse/charts/releases/tag/lakefs-0.8.3)
