### ISSUE TITLE
Deploy error using 0.7 lake fs chart version

### ISSUE THREAD

**Issue by luancaarvalho** [treeverse/charts#152]
Hello Guys!

I tried to run the quickstart of lake fs helm chart deploy, but I couldn't able, because I got the image error: 
![image](https://user-images.githubusercontent.com/34407796/206277833-75d2abd5-d955-40ab-8d92-0a0c7061c11e.png)

Ps: kubernetes version - 1.24.1 and Helm chart version: 0.7

**Comment by guy-har** [comment]
Closed by #157
