### ISSUE TITLE
Upgrade error from 0.69.0 version to 0.80.0

### ISSUE THREAD

**Issue by luancaarvalho** [treeverse/charts#156]
Hello guys !

 I tried to update from 0.69 version to 0.80 and I got this error, even using the default values:
 
```
 helm upgrade --history-max=5 --install=true --namespace=argocd --timeout=10m0s --values=/home/shell/helm/values-lakefs-0.8.0.yaml --version=0.8.0 --wait=true lakefs /home/shell/helm/lakefs-0.8.0.tgz
Error: UPGRADE FAILED: template: lakefs/templates/deployment.yaml:65:14: executing "lakefs/templates/deployment.yaml" at <include "lakefs.env" .>: error calling include: template: lakefs/templates/_env.tpl:3:39: executing "lakefs.env" at <.Values.secrets.databaseConnectionString>: nil pointer evaluating interface {}.databaseConnectionString
```

Ways to reproduce:
Just install the 0.69.0 version using the default values and try to update to 0.80.0 version

How to solve:

Use the feature/parentasized-chart branch and change the line 3 of` lakefs/templates/_env.tpl ` to:
`((.Values.secrets).databaseConnectionString)`

Special thanks for @Jonathan-Rosenberg to solve that error !

**Comment by Jonathan-Rosenberg** [comment]
Thank you for discovering this issue @luancaarvalho!
The problem here isn't specifically related to the upgrade but to the syntax used in the `_env.tpl` partial file.
