### ISSUE TITLE
Recommended port forward command label does not match label on LakeFS pod

### ISSUE THREAD

**Issue by avaidyanatha** [treeverse/charts#46]
This is the command I was given when I ran the helm chart: 
```export POD_NAME=$(kubectl get pods --namespace default -l "app=my-lakefs" -o jsonpath="{.items[0].meta.name}")```

That returned this error:
```
error: error executing jsonpath "{.items[1].metadata.name}": Error executing template: array index out of bounds: index 1, length 0
```

Which is because the label set on the pod is just `lakefs`

```
Name:           my-lakefs-78766c7c99-288t2
Namespace:      default
Priority:       0
Node:           minikube/192.168.39.164
Start Time:     Wed, 13 Jan 2021 17:55:30 -0800
Labels:         app=lakefs
                app.kubernetes.io/instance=my-lakefs
                app.kubernetes.io/name=lakefs
                pod-template-hash=78766c7c99
```

I suspect that `lakefs.fullname` is not being set correctly here: https://github.com/treeverse/charts/blob/master/charts/lakefs/templates/_helpers.tpl 

Not a huge deal, just a heads up!

**Comment by johnnyaug** [comment]
@avaidyanatha thanks for opening this issue!

**Comment by itaiad200** [comment]
Not sure why automatic closing of this issue didn't happen with #47
