### ISSUE TITLE
Permissions issues when deploying to OpenShift

### ISSUE THREAD

**Issue by tvanderwal-lmco** [treeverse/charts#79]
The LakeFS pod when initialized will try and create a directory structure for `/data/` if it doesn't exist, however in OpenShift pods can't run as root by default and generally isn't allowed in enterprise installations. My work around was to add an emptyDir by default to this directory.

**Comment by itaiad200** [comment]
This is configurable with `blockstore.local.path`, default value is `~/data/lakefs/block` and this issue only exists on local blockstore.

**Comment by itaiad200** [comment]
@tvanderwal-lmco closing for now, please reopen if it didn't solve your issue.

**Comment by tvanderwal-lmco** [comment]
@itaiad200 i did get a merge request in that fixes this, sorry I missed closing it. 

Though just for clarification this issue happens regardless of your blockstore config. What happens in properly configured open shift clusters containers are not allowed do to run as root. So when LakeFS starts up it tries to create /data of it doesn’t exist throwing a permissions error out since it can’t write to /.

**Comment by itaiad200** [comment]
Thanks for the clarification and contribution!
